/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package grpc.playground

import grpc.playground.blog.service.BlogServiceImpl
import io.grpc.Server
import io.grpc.ServerBuilder

class BlogServer private constructor(
	val port: Int,
	private val server: Server
) {
	constructor(port: Int): this(
		port,
		ServerBuilder.forPort(port)
			.addService(BlogServiceImpl())
			.build()
	)

	fun start() {
		println("Starting server ...")

		server.start()

		println("Server started ..., listening on port $port")

		Runtime.getRuntime().addShutdownHook(Thread {
			println("Shutting down server ...")
			server.shutdown()
			println("Server shut down")
		})
	}

	fun blockAndAwaitTermination() {
		server.awaitTermination()
	}
}

fun main(args: Array<String>) {
	val server = BlogServer(50051)

	server.start()
	server.blockAndAwaitTermination()
}
